/***************************************************************************
 *                                                                         *
 *       Shanghai Zongmu Technology Co. Ltd.                               *
 *                                                                         *
 *    Copyright (c) 2018 by Shanghai Zongmu Technology Co. Ltd.            *
 *    All rights reserved.                                                 *
 *                                                                         *
 *    This Software is protected by People's Republic of China copyright   *
 *    laws and international treaties.  You may not reverse engineer,      *
 *    decompile or disassemble this Software.                              *
 *                                                                         *
 *    WARNING:                                                             *
 *    This Software contains Shanghai Zongmu Technology Co. Ltd.'s         *
 *    confidential and proprietary information. UNAUTHORIZED COPYING,      *
 *    USE, DISTRIBUTION, PUBLICATION, TRANSFER, SALE, RENTAL OR DISCLOSURE *
 *    IS PROHIBITED AND MAY RESULT IN SERIOUS LEGAL CONSEQUENCES.  Do not  *
 *    copy this Software without Shanghai Zongmu Technology Co. Ltd.'s     *
 *    express written permission.   Use of any portion of the contents of  *
 *    this Software is subject to and restricted by your written agreement *
 *    with Shanghai Zongmu Technology Co. Ltd.                             *
 *                                                                         *
 ***************************************************************************/
#ifndef LIVE_MESSAGE_SOC_TO_OEM_TYPES_H_
#define LIVE_MESSAGE_SOC_TO_OEM_TYPES_H_

#define LIVE_MSG_CATEGORY_BITS  8
#define LIVE_MSG_CATEGORY_SHIFT (sizeof(unsigned short) * 8 - (LIVE_MSG_CATEGORY_BITS))
#define LIVE_MSG_CATEGORY_START(category)   ((category) <<  LIVE_MSG_CATEGORY_SHIFT)

#define LIVE_MSG_CATEGORY_OEM_SOC_TO_MCU 17

/*
  Define the OEM specific live msg (soc sned, mcu receive) here.
  These msgs only be used by MCU and customized node (such as UI application).
  !!!!! DO NOT use these msg in any other modules !!!! 
*/

#define DDS_SOC_TO_MCU_ID_START 16

enum {
    LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START = LIVE_MSG_CATEGORY_START(LIVE_MSG_CATEGORY_OEM_SOC_TO_MCU) + DDS_SOC_TO_MCU_ID_START,

	LIVE_MSG_DDS_NTF_LOCSTALL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 0,
	LIVE_MSG_DDS_NTF_PHYSTALL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 1,
	LIVE_MSG_DDS_NTF_TAILGATESYSST = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 2,
	LIVE_MSG_DDS_NTF_PHYST = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 3,
	LIVE_MSG_DDS_NTF_TURNLISWTREQINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 4,
	LIVE_MSG_DDS_NTF_HDLAMPSWTREQINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 5,
	LIVE_MSG_DDS_NTF_FOGINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 6,
	LIVE_MSG_DDS_NTF_HIBEAMINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 7,
	LIVE_MSG_DDS_NTF_SRVOPERINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 8,
	LIVE_MSG_DDS_NTF_BRKLIFLTINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 9,
	LIVE_MSG_DDS_NTF_BRKLIINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 10,
	LIVE_MSG_DDS_NTF_HIBEAMFLTINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 11,
	LIVE_MSG_DDS_NTF_LOBEAMFLTINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 12,
	LIVE_MSG_DDS_NTF_TURNLIFLTINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 13,
	LIVE_MSG_DDS_NTF_LOBEAMINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 14,
	LIVE_MSG_DDS_NTF_POSNLIINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 15,
	LIVE_MSG_DDS_NTF_TURNLIINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 16,
	LIVE_MSG_DDS_NTF_WIPERRLSSTS = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 17,
	LIVE_MSG_DDS_NTF_WIPERSTSINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 18,
	LIVE_MSG_DDS_NTF_LISNSRMOD = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 19,
	LIVE_MSG_DDS_NTF_SEATSTS = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 20,
	LIVE_MSG_DDS_NTF_SENDPROTODATA = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 21,
	LIVE_MSG_DDS_RR_HU_LANECHANGGEREQ = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 22,
	LIVE_MSG_DDS_RR_HU_VC_ACCACTIVE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 23,
	LIVE_MSG_DDS_RR_HU_VC_CRUISESETDISTANCE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 24,
	LIVE_MSG_DDS_RR_HU_VC_CRUISESETSPEED = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 25,
	LIVE_MSG_DDS_NTF_SWTINFO = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 26,
	LIVE_MSG_DDS_RR_HU_CSLAENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 27,
	LIVE_MSG_DDS_RR_HU_CSLMODE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 28,
	LIVE_MSG_DDS_RR_HU_CURISEMODE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 29,
	LIVE_MSG_DDS_RR_HU_OVERSPEEDSOUNDWARENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 30,
	LIVE_MSG_DDS_RR_HU_UDLCENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 31,
	LIVE_MSG_DDS_NTF_POSWINALL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 32,
	LIVE_MSG_DDS_NTF_BLERPACTL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 33,
	LIVE_MSG_DDS_NTF_ADAS_MAPNAVIGATIONSIGNAL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 34,
	LIVE_MSG_DDS_NTF_ADAS_MAPCOMMONSIGNAL = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 35,
	LIVE_MSG_DDS_RR_HU_AUTODRIVESTYLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 36,
	LIVE_MSG_DDS_RR_HU_ADACCSTYLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 37,
	LIVE_MSG_DDS_RR_HU_ADCURVESTYLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 38,
	LIVE_MSG_DDS_RR_HU_VEHICLESTARTREMINDENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 39,
	LIVE_MSG_DDS_RR_HUSET_CURISEMODE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 40,
	LIVE_MSG_DDS_RR_HU_RCWENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 41,
	LIVE_MSG_DDS_RR_HU_SEAMODE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 42,
	LIVE_MSG_DDS_RR_HU_BSDLCASETTING = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 43,
	LIVE_MSG_DDS_RR_HU_BSDLCAREMINDMODE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 44,
	LIVE_MSG_DDS_RR_HU_REDLIGHTREMINDENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 45,
	LIVE_MSG_DDS_RR_HU_FORWARDCOLLIASTTYPE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 46,
	LIVE_MSG_DDS_RR_HU_FORWARDCOLLIASTSENSTYLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 47,
	LIVE_MSG_DDS_RR_HU_REARCOLLIASTTYPE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 48,
	LIVE_MSG_DDS_RR_HU_LASMODESELECTION = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 49,
	LIVE_MSG_DDS_RR_HU_LASWARNINGMODESELECTION = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 50,
	LIVE_MSG_DDS_RR_HU_CESENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 51,
	LIVE_MSG_DDS_RR_HU_ELKENABLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 52,
	LIVE_MSG_DDS_EVT_GPSDATA = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 53,
	LIVE_MSG_DDS_NTF_ACTSENMOSWITST = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 54,
	LIVE_MSG_DDS_NTF_ACTCAMPSWITSET = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 55,
	LIVE_MSG_DDS_NTF_VIUGEARSHIFTPOSN = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 56,
	LIVE_MSG_DDS_NTF_LANELEDFLTSTS = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 57,
	LIVE_MSG_DDS_RR_HU_ADSTARTSTYLE = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 58,
	LIVE_MSG_DDS_RR_HU_SEAONOFF = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 59,
	LIVE_MSG_DDS_RR_HU_BSDLCAONOFF = LIVE_MSG_OEM_DDS_SOC_TO_MCU_ID_START + 60,

};

#endif  /* LIVE_MESSAGE_SOC_TO_OEM_TYPES_H_ */
