/****************************************************************
  Generated by Autocore DDS IDL to C Translator
  File name: logconfig.h
  Source: logconfig.idl
  AutoCore DDS: V1.6.4
*****************************************************************/
#ifndef DDSC_LOGCONFIG_H
#define DDSC_LOGCONFIG_H

#include "changan/rpc_types.h"

#include "changan/Common.h"

#include "dds/ddsc/dds_public_impl.h"

#include "dds/dds.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct carDrive_logconfig_SETSOALOG_In
{
  char * logLevel;
  char * logDir;
} carDrive_logconfig_SETSOALOG_In;

#define carDrive_logconfig_SETSOALOG_Hash 108265473
typedef struct carDrive_logconfig_Call
{
  int32_t _d;
  union
  {
    struct carDrive_logconfig_SETSOALOG_In SETSOALOG;
    DDS_RPC_UnknownOperation unknownOp;
  } _u;
} carDrive_logconfig_Call;

typedef struct carDrive_logconfig_Request
{
  struct DDS_RPC_RequestHeader header;
  struct carDrive_logconfig_Call data;
} carDrive_logconfig_Request;

extern const dds_topic_descriptor_t carDrive_logconfig_Request_desc;

#define carDrive_logconfig_Request__alloc() \
((carDrive_logconfig_Request*) dds_alloc (sizeof (carDrive_logconfig_Request)));

#define carDrive_logconfig_Request_free(d,o) \
dds_sample_free ((d), &carDrive_logconfig_Request_desc, (o))

typedef struct carDrive_logconfig_SETSOALOG_Out
{
  char * return_;
} carDrive_logconfig_SETSOALOG_Out;

typedef struct carDrive_logconfig_Return
{
  int32_t _d;
  union
  {
    struct carDrive_logconfig_SETSOALOG_Out SETSOALOG;
    DDS_RPC_UnknownOperation unknownOp;
  } _u;
} carDrive_logconfig_Return;

typedef struct carDrive_logconfig_Reply
{
  struct DDS_RPC_ReplyHeader header;
  struct carDrive_logconfig_Return data;
} carDrive_logconfig_Reply;

extern const dds_topic_descriptor_t carDrive_logconfig_Reply_desc;

#define carDrive_logconfig_Reply__alloc() \
((carDrive_logconfig_Reply*) dds_alloc (sizeof (carDrive_logconfig_Reply)));

#define carDrive_logconfig_Reply_free(d,o) \
dds_sample_free ((d), &carDrive_logconfig_Reply_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LOGCONFIG_H */
